apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: fouz-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fouz-role
subjects:
  - kind: ServiceAccount
    name: fouz-sa