apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: user-pipelinerun 
spec:
  pipelineRef:
    name: user-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: level3-project
  params:
    - name: CONTEXT
      value: "/workspace/level3-project/user"
    - name: DOCKERFILE
      value: "/workspace/level3-project/user/Dockerfile"
    - name: pathToYamlFile
      value: "level3-project/user/user-dep.yml"
    - name: pathToSvcYamlFile
      value: "level3-project/user/svc.yml"
    - name: imageUrl
      value: "fouz/user"
    - name: imageTag
      value: "latest"
    - name: IMAGE
      value: "fouz/user"
      
  serviceAccountName: fouz-sa
