apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: front-end-pipelinerun 
spec:
  pipelineRef:
    name: front-end-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: level3-project
  params:
    - name: CONTEXT
      value: "/workspace/level3-project/front-end"
    - name: DOCKERFILE
      value: "/workspace/level3-project/front-end/Dockerfile"
    - name: pathToYamlFile
      value: "level3-project/front-end/front-end-dep.yml"
    - name: pathToSvcYamlFile
      value: "level3-project/front-end/svc.yml"
    - name: pathToIngressYamlFile
      value: "level3-project/front-end/ingress.yml"
    - name: imageUrl
      value: "fouz/front-end"
    - name: imageTag
      value: "latest"
    - name: IMAGE
      value: "fouz/front-end"   
  serviceAccountName: fouz-sa
