apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: payment-pipelinerun 
spec:
  pipelineRef:
    name: payment-pipeline
  resources:
    - name: level3-project
      resourceRef:
        name: level3-project
  params:
    - name: CONTEXT
      value: "/workspace/level3-project/payment"
    - name: DOCKERFILE
      value: "/workspace/level3-project/payment/Dockerfile"
    - name: pathToYamlFile
      value: "level3-project/payment/payment-dep.yml"
    - name: pathToSvcYamlFile
      value: "level3-project/payment/svc.yml"
  
    - name: imageUrl
      value: "fouz/payment"
    - name: imageTag
      value: "latest"
    - name: IMAGE
      value: "fouz/payment"   
  serviceAccountName: fouz-sa
