apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-js-test-pipeline
spec:
  resources:
    - name: level3-project
      type: git
  params:
    - name: IMAGE
      type: string
      default: "fouz/e2e-js-test"
    - name: DOCKERFILE
      type: string
      default: "/workspace/project-level3/e2e-js-test/Dockerfile"
    - name: CONTEXT
      type: string
      default: "/workspace/project-level3/e2e-js-test"
    - name: imageUrl
      type: string
      default: "fouz/e2e-js-test"
    - name: imageTag
      type: string
      default: "latest"
    - name: pathToYamlFile
      type: string
      default: "level3-project/e2e-js-test/dep.yaml"
  tasks:
  - name: build-push-image
    taskRef:
      name: e2e-js-test-task
    params:
      - name: IMAGE
        value: "$(params.IMAGE)"
      - name: DOCKERFILE
        value: "$(params.DOCKERFILE)"
      - name: CONTEXT
        value: "$(params.CONTEXT)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: run-test
    taskRef:
      name: e2e-js-test-task-run
    runAfter:
      - build-push-image
    params:
      - name: imageUrl
        value: "$(params.imageUrl)"
      - name: imageTag
        value: "$(params.im`ageTag)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project
  - name: deploy-prod
    taskRef:
      name: e2e-js-test-prod
    runAfter:
      - build-push-image
      - run-test
    params:
      - name: pathToYamlFile
        value: "$(params.pathToYamlFile)"
    resources:
      inputs:
        - name: level3-project
          resource: level3-project